POST https://snowball-income.com/extapi/api/backtest/calc
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImZkNDBjMTY5LWNkNmEtNDg3Mi1hYmQyLTQwMTYyYjdmOTg3ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJwb3R5a2lvbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJwb3R5a2lvbkBnbWFpbC5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6Ik1JSDdRNEM0Q01XTU9QV1pKWERGMk8yUjJGT0VVN042IiwiRGlzcGxheU5hbWUiOiJOaWtpdGEgTGV5Ym92aWNoIiwiUGF0cmVvbkVtYWlsIjoiIiwiU3Vic2NyaXB0aW9uVHlwZSI6IlRpZXIxIiwiSXNBY3RpdmUiOiJUcnVlIiwiRXhwaXJhdGlvbkRhdGUiOiIwNC4wMS4yMDI0IDE0OjIwOjQzIiwiSXNBZG1pbiI6IkZhbHNlIiwiZXhwIjoxNjg2MjA2MjU5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMzNS8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0NDMzNS8ifQ.Ka01dVUR52UeHfKrNF_i6InSboM8rBWEDbdEobIUkf8
Content-Type: application/json

{

}

###

POST https://snowball-income.com/extapi/api/backtest-result/stats
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImZkNDBjMTY5LWNkNmEtNDg3Mi1hYmQyLTQwMTYyYjdmOTg3ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJwb3R5a2lvbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJwb3R5a2lvbkBnbWFpbC5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6Ik1JSDdRNEM0Q01XTU9QV1pKWERGMk8yUjJGT0VVN042IiwiRGlzcGxheU5hbWUiOiJOaWtpdGEgTGV5Ym92aWNoIiwiUGF0cmVvbkVtYWlsIjoiIiwiU3Vic2NyaXB0aW9uVHlwZSI6IlRpZXIxIiwiSXNBY3RpdmUiOiJUcnVlIiwiRXhwaXJhdGlvbkRhdGUiOiIwNC4wMS4yMDI0IDE0OjIwOjQzIiwiSXNBZG1pbiI6IkZhbHNlIiwiZXhwIjoxNjg2MjA2MjU5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMzNS8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0NDMzNS8ifQ.Ka01dVUR52UeHfKrNF_i6InSboM8rBWEDbdEobIUkf8
Content-Type: application/json

{
  "key": "{{ key }}",
  "currency": "RUB",
  "include": "common.summary,common.holdings,scores.beta"
}
